version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - mysql-data:/var/lib/mysql

  db:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cristopherq_bd
      - MYSQL_USER=cquintana
      - MYSQL_PASSWORD=cristopher2023
      - MYSQL_ROOT_PASSWORD=quintana2023adm
volumes:
  mysql-data: