version: '3'

services:
  db:
    image: postgres:14.8
    environment:
      POSTGRES_PASSWORD: cristopher2023
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1438:1438"
    depends_on:
      - db
    environment:
      - DB_NAME=predictor
      - DB_USER=cristopher
      - DB_PASSWORD=cristopher2023
      - DB_HOST=db
      - DB_PORT=5432