# Generated by Django 4.2.2 on 2023-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciondata',
            name='available_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='condition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='permalink',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='seller_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='seller_nickname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='shipping',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='sold_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicaciondata',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
